[meta]
name = "ManiaExchange Random Map Picker"
author = "Greep"
category = "TMX"
perms = "paid"
siteid = 124

version = "2.5.3"

[script]
optional_dependencies = [ "ManiaExchange", "ChaosMode", "NadeoServices", "MLHook", "MLFeedRaceData", "BetterChat", "BetterRoomManager" ]

exports = [ "src/Exports/Exports.as" ]

timeout = 0

#defines = [ "FORCE_NO_DEV" ]